cabecera = ("{:^30}\n{:10}{:>15}{:>10}\n{}\n".format(
    "Alumnos", "Dni", "Nombre", "Nota", "*" * 30))
dni = input("dame el dni")
nombre = input("dame el nombre")
nota = float(input("dame la nota"))
datos = "{:10}{:>15}{:>10.4f}\n".format(dni, nombre, nota)
print(cabecera + datos)
dni2 = input("dame el dni")
nombre2 = input("dame el nombre")
nota2 = float(input("dame la nota"))
datos2 = "{:10}{:>15}{:>10.4f}\n".format(dni2, nombre2, nota2)
print(cabecera + datos + datos2)
dni3 = input("dame el dni")
nombre3 = input("dame el nombre")
nota3 = float(input("dame la nota"))
datos3 = "{:10}{:>15}{:>10.4f}\n".format(dni3, nombre3, nota3)
print(cabecera + datos + datos2 + datos3)
