cabecera = ("{:^30}\n{:10}{:>10}{:>10}\n{}\n".format(
    "lista de la compra", "Articulo", "Cantidad", "precio", "*" * 30))
articulo = input("dame un articulo")
cantidad = input("dame la cantidad")
precio = float(input("dame el precio"))
datos = "{:10}{:>10}{:>10.2f}\n".format(articulo, cantidad, precio)
print(cabecera + datos)
articulo2 = input("dame un articulo")
cantidad2 = input("dame la cantidad")
precio2 = float(input("dame el precio"))
datos2 = "{:10}{:>10}{:>10.2f}\n".format(articulo2, cantidad2, precio2)
print(cabecera + datos + datos2)
articulo3 = input("dame un articulo")
cantidad3 = input("dame la cantidad")
precio3 = float(input("dame el precio"))
datos3 = "{:10}{:>10}{:>10.2f}\n".format(articulo3, cantidad3, precio3)
print(cabecera + datos + datos2 + datos3)
